name: The name of your workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
